version: '3.3'

services:
  hashpaw-api:
    container_name: hashpaw-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000

    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/hashpaw-next
    working_dir: /usr/src/hashpaw-next

    networks:
      - client-network

    #For Production
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
#hashpaw-next: localhost:4000
#hashpash-api: localhost:4001 => container:3007
#hashpash-batch: localhost:4002 => container:3008
